version: '2'

services:
    webserver:
        image: "webserver"
        depends_on:
            - authentication
            - photo
            - vote
            - comment
            - profile
        ports:
            - "4999:4999"
        restart: always
        environment:
        - "affinity:com.mariadb.host!=webserver"
        - "PORT=4999"
        - "PROFILE_URL=http://profile:5000"
        - "AUTHENTICATION_URL=http://authentication:5001"
        - "PHOTO_URL=http://photo:5002"
        - "VOTE_URL=http://vote:5003"
        - "COMMENT_URL=http://comment:5004"
        labels:
        - "com.mariadb.host=webserver"
    authentication:
        image: "authenticationsvc"
        depends_on: 
            - registrator
        ports:
            - "5001:5001"
        restart: always 
        environment:
        - "PORT=5001"
        - "DB_USERNAME=profile_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=maxscale"
        - "DB_PORT=3308"
        - "DB=ProfileService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=authenticationsvc"
        labels:
        - "com.mariadb.host=authenticationsvc"
    photo:
        image: "photosvc"
        depends_on: 
            - registrator
        ports:
            - "5002:5002"
        restart: always 
        environment:
        - "PORT=5002"
        - "COMMENT_SERVICE_URL=http://comment:5004/"
        - "VOTE_SERVICE_URL=http://vote:5003/"
        - "PROFILE_SERVICE_URL=http://profile:5000/"
        - "DB_USERNAME=photo_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=maxscale"
        - "DB_PORT=3308"
        - "DB=PhotoService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=photosvc"
        labels:
        - "com.mariadb.host=photosvc"
    vote:
        image: "votesvc"
        depends_on: 
            - registrator
        ports:
            - "5003:5003"
        restart: always
        environment:
        - "PORT=5003"
        - "DB_USERNAME=vote_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=maxscale"
        - "DB_PORT=3308"
        - "DB=VoteService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=votesvc"
        labels:
        - "com.mariadb.host=votesvc"
    comment:
        image: "commentsvc"
        depends_on: 
            - registrator
        ports:
            - "5004:5004"
        restart: always
        environment:
        - "PORT=5004"
        - "PROFILE_SERVICE_URL=http://profile:5000/"
        - "DB_USERNAME=comment_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=maxscale"
        - "DB_PORT=3308"
        - "DB=CommentService"
        - "affinity:com.mariadb.host!=commentsvc"
        labels:
        - "com.mariadb.host=commentsvc"
    profile:
        image: "profilesvc"
        depends_on: 
            - registrator
        ports:
            - "5000:5000"
        restart: always
        environment:
        - "PORT=5000"
        - "DB_USERNAME=profile_service"
        - "DB_PASSWORD=password"
        - "DB_HOST=maxscale"
        - "DB_PORT=3308"
        - "DB=ProfileService"
        - "SECRET_KEY=ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        - "affinity:com.mariadb.host!=profilesvc"
        labels:
        - "com.mariadb.host=profilesvc"
    db:
        image: bstaijen/mariadb-microservice-database:latest
        depends_on: 
            - registrator
        restart: always
        environment:
        - "MYSQL_ROOT_PASSWORD=password"
        - "CLUSTER_NAME=galeracluster"
        - "CONSUL_HOST=consul:8500"
        - "SERVICE_NAME=mariadb-galera"
        - "SERVICE_TAGS=mariadb,galera,db"
        - "affinity:com.mariadb.host!=galeracluster"
        labels:
        - "com.mariadb.host=galeracluster"
        ports:
        - 3306:3306
        - 4567-4568:4567-4568
        - 4444:4444
    registrator:
        image: gliderlabs/registrator:master
        depends_on: 
            - consul
        hostname: registrator
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal consul://consul:8500
        restart: always
        environment:
        - "affinity:com.mariadb.host!=registrator"
        labels:
        - "com.mariadb.host=registrator"
    consul:
        image: "progrium/consul:latest"
        hostname: "consul"
        ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
        command: "-server -bootstrap -ui-dir /ui"
        restart: always