version: '2'

services:
    registrator:
        image: gliderlabs/registrator:v7
        depends_on: 
            - consul
        hostname: registrator
        volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal consul://consul:8500
        restart: always
        environment:
        - "affinity:com.mariadb.host!=registrator"
        labels:
        - "com.mariadb.host=registrator"
    consul:
        image: "progrium/consul:latest"
        hostname: "consul"
        ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
        command: "-server -bootstrap -ui-dir /ui"
        restart: always
    vizualizer:
        image: bstaijen/mariadb-microservice-vizualizersvc:demo
        ports:
        - 3000:3000
        environment:
        - SWARM_HOST
        - SWARM_CA
        - SWARM_KEY
        - SWARM_CERT
        - "constraint:node==master"
        restart: always